# ---------------------------------------------------------------------------
# Maleos build system
#
#   make          Build build/kernel.elf
#   make iso      Package a bootable ISO (build/maleos.iso)
#   make run      Boot the ISO in QEMU
#   make debug    Boot paused with a GDB server on localhost:1234
#   make test     Headless boot test with test disks (used by CI)
#   make input-test  Keyboard test: injects keys through the QEMU monitor
#   make shell-test  Boot to the shell, run ~40 commands over the serial console
#   make disks    Build the ext2 test disk images (needed by run/debug to see disks)
#   make format   Format C sources with clang-format
#   make clean    Remove build artifacts
#   make help     Show this message
#
# Toolchain: uses x86_64-elf-* if installed (see scripts/build-toolchain.sh),
# otherwise falls back to the host GCC/binutils in freestanding mode.
# Override any tool on the command line, e.g.  make CC=clang
# ---------------------------------------------------------------------------

ARCH       := x86_64
BUILD_DIR  := build
ISO_DIR    := $(BUILD_DIR)/isodir
KERNEL     := $(BUILD_DIR)/kernel.elf
ISO        := $(BUILD_DIR)/maleos.iso

# Prefer the cross toolchain, fall back to host tools.
ifneq ($(shell command -v x86_64-elf-gcc 2>/dev/null),)
CROSS ?= x86_64-elf-
else
CROSS ?=
endif

# make predefines CC=cc, so only override it when the user did not set it.
ifeq ($(origin CC),default)
CC      := $(CROSS)gcc
endif
LD      := $(CROSS)ld
NASM    ?= nasm
QEMU    ?= qemu-system-x86_64
GRUB_MKRESCUE ?= grub-mkrescue

CFLAGS  := -std=c11 -ffreestanding -fstack-protector-strong -mstack-protector-guard=global -fno-pic -mno-red-zone \
           -mcmodel=kernel -mno-mmx -mno-sse -mno-sse2 \
           -fno-tree-loop-distribute-patterns \
           -Wall -Wextra -Werror -O2 -g -Isrc/include -MMD -MP
ASFLAGS := -f elf64 -g -F dwarf
LDFLAGS := -n -nostdlib -z noexecstack -z max-page-size=0x1000 -T linker.ld

C_SRCS   := $(shell find src -name '*.c' 2>/dev/null)
ASM_SRCS := $(shell find src -name '*.asm' 2>/dev/null)
OBJS     := $(patsubst src/%.c,$(BUILD_DIR)/%.c.o,$(C_SRCS)) \
            $(patsubst src/%.asm,$(BUILD_DIR)/%.asm.o,$(ASM_SRCS))

# ---- user space (Phase 6): a tiny libc, programs in user/bin, test programs in user/test ----
USER_CFLAGS  := -std=c11 -ffreestanding -fstack-protector-strong -mstack-protector-guard=global -fno-pic -mno-mmx -mno-sse \
                -mno-sse2 -fno-tree-loop-distribute-patterns -Wall -Wextra -Werror -O2 -g \
                -Isrc/include -Iuser/include -MMD -MP
USER_LDFLAGS := -n -nostdlib -z noexecstack -z max-page-size=0x1000 -T user/user.ld
AR           := $(CROSS)ar

USER_OBJ_DIR  := $(BUILD_DIR)/user/obj
USER_CRT0     := $(USER_OBJ_DIR)/lib/crt0.o
USER_LIB_SRCS := $(filter-out user/lib/crt0.c,$(wildcard user/lib/*.c))
USER_LIB      := $(BUILD_DIR)/user/libulib.a
USER_NAMES    := $(patsubst user/bin/%.c,%,$(wildcard user/bin/*.c))
USER_TESTS    := $(patsubst user/test/%.c,%,$(wildcard user/test/*.c))
USER_BINS     := $(addprefix $(BUILD_DIR)/user/bin/,$(USER_NAMES)) \
                 $(addprefix $(BUILD_DIR)/user/test/,$(USER_TESTS))
USER_ALL_OBJS := $(USER_CRT0) $(patsubst user/%.c,$(USER_OBJ_DIR)/%.o,$(USER_LIB_SRCS)) \
                 $(patsubst user/bin/%.c,$(USER_OBJ_DIR)/bin/%.o,$(wildcard user/bin/*.c)) \
                 $(patsubst user/test/%.c,$(USER_OBJ_DIR)/test/%.o,$(wildcard user/test/*.c))

# Attach the test disks to `make run` / `make debug` when they exist (see `make disks`).
DISK_FLAGS := $(if $(wildcard build/disks/ide.img),-drive file=build/disks/ide.img,format=raw,if=ide,index=0 \
              -drive file=build/disks/sata.img,format=raw,if=none,id=sata0 \
              -device ich9-ahci,id=ahci -device ide-hd,drive=sata0,bus=ahci.0)

QEMU_FLAGS := -cdrom $(ISO) -m 256M -serial stdio -no-reboot $(DISK_FLAGS)

.PHONY: all iso run debug test input-test shell-test disks format clean help user
all: $(KERNEL)

user: $(USER_BINS)

# Header dependencies (generated by -MMD): editing a header rebuilds everything that includes it.
-include $(OBJS:.o=.d)

$(BUILD_DIR)/%.c.o: src/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(USER_OBJ_DIR)/%.o: user/%.c
	@mkdir -p $(dir $@)
	$(CC) $(USER_CFLAGS) -c $< -o $@

$(USER_LIB): $(patsubst user/%.c,$(USER_OBJ_DIR)/%.o,$(USER_LIB_SRCS))
	@mkdir -p $(dir $@)
	rm -f $@ && $(AR) rcs $@ $^

$(BUILD_DIR)/user/bin/%: $(USER_OBJ_DIR)/bin/%.o $(USER_CRT0) $(USER_LIB) user/user.ld
	@mkdir -p $(dir $@)
	$(LD) $(USER_LDFLAGS) -o $@ $(USER_CRT0) $< $(USER_LIB)

$(BUILD_DIR)/user/test/%: $(USER_OBJ_DIR)/test/%.o $(USER_CRT0) $(USER_LIB) user/user.ld
	@mkdir -p $(dir $@)
	$(LD) $(USER_LDFLAGS) -o $@ $(USER_CRT0) $< $(USER_LIB)

-include $(USER_ALL_OBJS:.o=.d)

$(BUILD_DIR)/%.asm.o: src/%.asm
	@mkdir -p $(dir $@)
	$(NASM) $(ASFLAGS) $< -o $@

$(KERNEL): $(OBJS) linker.ld
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

iso: $(ISO)

INITRD     := $(BUILD_DIR)/initrd.tar
INITRD_SRC := $(shell find initrd -type f 2>/dev/null) scripts/mkinitrd.sh $(USER_BINS)

$(INITRD): $(INITRD_SRC)
	./scripts/mkinitrd.sh $@ $(BUILD_DIR)/user

$(ISO): $(KERNEL) $(INITRD) iso/boot/grub/grub.cfg
	@rm -rf $(ISO_DIR)
	@mkdir -p $(ISO_DIR)/boot/grub
	cp $(KERNEL) $(ISO_DIR)/boot/kernel.elf
	cp $(INITRD) $(ISO_DIR)/boot/initrd.tar
	cp iso/boot/grub/grub.cfg $(ISO_DIR)/boot/grub/grub.cfg
	$(GRUB_MKRESCUE) -o $@ $(ISO_DIR) 2>/dev/null

run: $(ISO)
	$(QEMU) $(QEMU_FLAGS)

debug: $(ISO)
	@echo "QEMU paused. Attach with:"
	@echo '  gdb -ex "target remote localhost:1234" -ex "symbol-file $(KERNEL)"'
	$(QEMU) $(QEMU_FLAGS) -s -S

test: $(ISO)
	./scripts/boot-test.sh $(ISO)

input-test: $(ISO)
	./scripts/input-test.sh $(ISO)

shell-test: $(ISO)
	python3 scripts/shell-test.py $(ISO)

disks:
	./scripts/mkdisks.sh build/disks

format:
	@command -v clang-format >/dev/null || { echo "clang-format not installed"; exit 1; }
	@find src user -name '*.c' -o -name '*.h' | xargs -r clang-format -i

clean:
	rm -rf $(BUILD_DIR)

help:
	@sed -n '3,13p' Makefile | sed 's/^# \{0,1\}//'
